image: docker:19.03.1

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

services:
- name: postgres:11.5-alpine
  alias: db
- name: docker:19.03.1-dind

variables:
  POSTGRES_USER: scaledger
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: scaledger
  POSTGRES_HOST: db

stages:
  - build
  - test
  - release
  - deploy

code_quality:
  except:
    - master

server-build:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd src/server
  script:
    - docker build --pull --cache-from $CI_REGISTRY_IMAGE/scaledger-server:latest -t $CI_REGISTRY_IMAGE/scaledger-server:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE/scaledger-server:$CI_COMMIT_REF_SLUG

server-release:
  stage: release
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd src/server
  script:
    - docker pull $CI_REGISTRY_IMAGE/scaledger-server:$CI_COMMIT_REF_SLUG
    - docker tag $CI_REGISTRY_IMAGE/scaledger-server:$CI_COMMIT_REF_SLUG $CI_REGISTRY_IMAGE/scaledger-server:latest
    - docker push $CI_REGISTRY_IMAGE/scaledger-server:latest
  only:
    - master

db:
  stage: test
  image: postgres:11.5-alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}
  before_script:
    - cd src/db/scripts
  script:
    - ./schema
    - ./seed