version: '3.1'
services:
  db:
    container_name: scaledger-db
    image: postgres:11.5-alpine
    ports:
      - '5432:5432'
    volumes:
      - ../src/db:/tasks
      - ../src/db/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: scaledger
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: scaledger
  server:
    container_name: scaledger-server
    image: scaledger-server:latest
    ports:
      - 5000:5000
    links:
      - db
    environment:
      DATABASE_URL: postgres://scaledger:changeme@db/scaledger
      PORT: 5000
      AUTH_DATABASE_URL: postgres://scaledger:changeme@db/scaledger
      NODE_ENV: development
      HOST: http://localhost:5000
    depends_on:
      - db